### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by jmerifjKriwe** [roe-dl/weewx-GTS#10]
Hi,

during the installation I get an issue :-(

`pi@nodered:~ $ wget -O weewx-GTS.zip https://github.com/roe-dl/weewx-GTS/archive/master.zip
--2021-08-02 16:21:57--  https://github.com/roe-dl/weewx-GTS/archive/master.zip
Auflösen des Hostnamens github.com (github.com)… 140.82.121.3
Verbindungsaufbau zu github.com (github.com)|140.82.121.3|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 302 Found
Platz: https://codeload.github.com/roe-dl/weewx-GTS/zip/master [folgend]
--2021-08-02 16:21:57--  https://codeload.github.com/roe-dl/weewx-GTS/zip/master
Auflösen des Hostnamens codeload.github.com (codeload.github.com)… 140.82.121.9
Verbindungsaufbau zu codeload.github.com (codeload.github.com)|140.82.121.9|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: nicht spezifiziert [application/zip]
Wird in »weewx-GTS.zip« gespeichert.

weewx-GTS.zip                       [ <=>                                                  ]  50,30K  --.-KB/s    in 0,09s

2021-08-02 16:21:58 (560 KB/s) - »weewx-GTS.zip« gespeichert [51506]

pi@nodered:~ $ sudo wee_extension --install weewx-GTS.zip
Request to install 'weewx-GTS.zip'
Extracting from zip archive weewx-GTS.zip
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 183, in install_from_dir
    shutil.copy(source_path, destination_path)
  File "/usr/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/weewx-GTS-master/bin/usr/dayboundarystats.py'
`

Do you have any idea what is happening and how I can fix it?

Kind regards

**Comment by roe-dl** [comment]
I see there is a typo in install.py. I uploaded a bug fix. Please, download the extension again and repeat installation. 

Or you can change 'usr' to 'user' in install.py within your copy and then re-run wee_extension.

**Comment by jmerifjKriwe** [comment]
Thanks :-)
