### ISSUE TITLE
Best Practice for using yearGDD / seasonGDD

### ISSUE THREAD

**Issue by c0by85** [roe-dl/weewx-GTS#11]
Hi,

i need some help again. What is the best practice for using yearGDD / seasonGDD with your gts plugin. When i run it with the following config, i already have 20 - 40 seconds to calculate.

```
time wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
wee_reports  24,37s user 5,16s system 91% cpu 32,265 total
```

normal time to calculate without yearGDD / seasonGDD.
```
time wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
wee_reports  5,47s user 0,40s system 74% cpu 7,872 total
```

here my config for testing with the **belchertown skin**.
```
[test]
title = Test
show_button = false
button_text = Test
start_at_midnight = true
time_length = year
[[yearGTS_]]
title = Test
line_gap_fraction = 0.04
yscale = 0,None,None
aggregate_type = avg
aggregate_interval = 86400
[[[GTS]]]
[[[yearGDD]]]
[[[seasonGDD]]]

```
or is only one calculation every 24h recommended?

**Comment by roe-dl** [comment]
It is almost the same configuration in my case, and it needs 1.07s to calculate according to the logs.

And yes, it would be enough to calculate it once a day.

I am not sure if `yscale = 0,None,None` works with Belchertown skin Highcharts graphs. 

It may help to save `yearGDD` and `seasonGDD` to the database. But I did not try that. So I cannot say whether it works. If you want to test that, do not forget to make a backup of your database and then add the two observation types by using the `wee_database` tool.

My configuration is as follows:
```
[year]
    # Chart Timespan Defaults
    title = "Dieses Jahr"
    show_button = true
    button_text = "Jahr"
    type = spline
    time_length = year
    tooltip_date_format = "dddd LL"
    aggregate_type = max
    aggregate_interval = 86400 # 1 day
    gapsize = 86400 # 1 day in seconds

    ...

    [[Vegetation]]
        title = "Vegetation"
        aggregate_type = avg
        yAxis_label = "Wachstumsgradtage"
        yAxis_softMin = 100
        yAxis_softMax = 200
        [[[GTS]]]
            observation_type = GTS
            name = "Gr&uuml;nlandtemperatursumme"
        [[[yearGDD]]]
            observation_type = yearGDD
            name = "Wachstumsgradtage"
        [[[seasonGDD]]]
            observation_type = seasonGDD
            name = "Saison"
```

**Comment by c0by85** [comment]
I tested it again with the code. No change, calculation still takes 24 seconds. Which system is used? I use a VM with 2 cores and 2 GB Ram. But Python uses only one core for calculation.

But I think it will come down to a calculation per 24 hours at night.

**Comment by roe-dl** [comment]
I use a VM with 2 cores, too. It has 4 GB RAM, of which are 0.5 GB used and 3.8 GB cache, according to `top`. Load average is 15% to 30%. The web server runs on the same machine. During creation of the reports WeeWX consumes about 100% of the CPU for a second or two, otherwise about 2%.

What says `top` on your machine?

**Comment by c0by85** [comment]
Nothing special.

![image](https://user-images.githubusercontent.com/25707747/128560457-6055f1c2-26df-4e34-95cc-84b3b89e09b3.png)

![image](https://user-images.githubusercontent.com/25707747/128560578-bd76dc55-2aa6-46f5-a4b2-26a90567a855.png)

**Comment by roe-dl** [comment]
Sorry, I cannot make sense out of this.

What is the second screenshot? I see 2 different instances of WeeWX there. The use the same PID file, but have different PIDs. If you really run 2 instances of WeeWX on the same database, that may be the reason.

**Comment by c0by85** [comment]
I think it was just an htop viewing error. Weewx only runs once. Unfortunately I do not know how to display the performance further.

```
ps aux | grep -i weewx | grep -v exclude
root      126395 12.7  3.9 1026696 79784 ?       Sl   16:45  41:31 python3 /usr/share/weewx/weewxd --daemon --pidfile=/var/run/weewx.pid /etc/weewx/weewx.conf
```
