### ISSUE TITLE
Reduce Decimal Places in Radiation KwH/msq

### ISSUE THREAD

**Issue by Pogs2004** [roe-dl/weewx-GTS#19]
Hi,

Thanks for a great extension! I have some logic in my templates that changes the output of $timestamp.radiation.energy_integral from Wh/m² to kWh/m² if the value is >= 1000:

```
<div class="col-6">
            #if $month.radiation.energy_integral.raw >= 1000 
            <h4 class='h2-responsive '>$month.radiation.energy_integral.kilowatt_hour_per_meter_squared.round(ndigits=1)</h4>
            #else
            <h4 class='h2-responsive '>$month.radiation.energy_integral</h4>
            #end if
</div>
```
Although using the .round tag rounds the output to 1 decimal place it still displays the trailing zeros:

<img width="469" alt="Screenshot 2023-01-31 at 11 53 49" src="https://user-images.githubusercontent.com/17429893/215753031-40e98edd-3c60-4834-895a-ad2a44268c38.png">

Is there any way to display this value to a single decimal place?

**Comment by roe-dl** [comment]
Use `.format("%.1f")` instead of `.round(ndigits=1)`.
