### ISSUE TITLE
Display values (CheetahGenerator)

### ISSUE THREAD

**Issue by kobi80** [roe-dl/weewx-GTS#2]
Wenn ich die GTS Variablen in HTLM einbinde, dann bekomme ich folgende Fehler beim Erstellen der HTLM Seiten

HTLM Einbettung im WEEWX Mobile Template
![image](https://user-images.githubusercontent.com/79660810/109318281-ed101080-784d-11eb-9440-12e9fd919703.png)

![image](https://user-images.githubusercontent.com/79660810/109317800-63f8d980-784d-11eb-9272-a28a04a9bf01.png)

**Comment by roe-dl** [comment]
Zunächst etwas Inhaltliches: `GTS` und `GTSdate` sind zwei unabhängige Werte. `GTSdate` zeigt **nicht** das Datum, für das `GTS` berechnet wurde. `$current.GTS` ist immer der Wert für den heutigen Tag. Mit Hilfe von `$day`, `$yesterday` usw. kann man auch die Wert früherer Tage bekommen.
`GTSdate` ist dagegen der Tag, an dem `GTS` die Marke von 200 übersteigt. Solange `GTS` kleiner als 200 ist, ist `GTSdate` undefiniert. 

Die Fehlermeldung kann ich nachvollziehen und werde sie mir ansehen.

**Comment by roe-dl** [comment]
Bitte als Workaround `$current.GTSdate` nehmen. Das liefert den im Moment gültigen Wert "N/A" und wird auch bis zum Jahresende den richtigen Wert liefern.

**Comment by roe-dl** [comment]
Es war einfacher, als ich dachte. Da fehlte noch etwas in der Funktion, die die zusammengefaßten Werte liefert, zu denen programmtechnisch auch `$day.GTSdate.last` gehört. 

Bitte die Extension einfach nochmal drüberinstallieren oder hier unter "Code" die Datei bin/user/GTS.py herunterladen und nach /usr/share/weewx/user/ kopieren. Danach WeeWX neu starten.

**Comment by kobi80** [comment]
tolle Arbeit. nun geht´s ohne Fehler. Super. Danke
![image](https://user-images.githubusercontent.com/79660810/109359684-29f7f980-7886-11eb-9217-fe775dc19012.png)
