### ISSUE TITLE
GTS Error on weewx starting

### ISSUE THREAD

**Issue by WernerKr** [roe-dl/weewx-GTS#22]
weewx[2453] ERROR user.GTS: dayET: no record (logged only once)
 weewx[2453] INFO user.GTS: GTS initialized 2023-01-01 00:04:43 
 weewx[2453] INFO user.GTS: GTS 73.15416391976729, 67 loops
 weewx[2453] ERROR weewx.cheetahgenerator: Evaluation of template /etc/weewx4/skins/Seasons/index.html.tmpl failed with exception '<class 'TypeError'>'
 weewx[2453] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx4/skins/Seasons/index.html.tmpl
 weewx[2453] ERROR weewx.cheetahgenerator: **** Reason: 'NoneType' object is not subscriptable
 weewx[2453] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 77, in get_scalar
 weewx[2453] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager, **option_dict)
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/GTS.py", line 570, in get_scalar
 weewx[2453] ERROR weewx.cheetahgenerator: ****      return weewx.units.convertStd(__x,record['usUnits'])
 weewx[2453] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable
 weewx[2453] ERROR weewx.cheetahgenerator: ****  
 weewx[2453] ERROR weewx.cheetahgenerator: ****  During handling of the above exception, another exception occurred:
 weewx[2453] ERROR weewx.cheetahgenerator: ****  
 weewx[2453] ERROR weewx.cheetahgenerator: ****  Traceback (most recent call last):
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 348, in generate
 weewx[2453] ERROR weewx.cheetahgenerator: ****      unicode_string = compiled_template.respond()
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx4_skins_Seasons_index_html_tmpl.py", line 748, in respond
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/lib/python3/dist-packages/Cheetah/Template.py", line 1707, in _handleCheetahInclude
 weewx[2453] ERROR weewx.cheetahgenerator: ****      self._CHEETAH__cheetahIncludes[_includeID].respond(trans)
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "_etc_weewx4_skins_Seasons_current_inc.py", line 537, in respond
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/tags.py", line 599, in __getattr__
 weewx[2453] ERROR weewx.cheetahgenerator: ****      vt = weewx.xtypes.get_scalar(obs_type, self.record, db_manager)
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/weewx/xtypes.py", line 81, in get_scalar
 weewx[2453] ERROR weewx.cheetahgenerator: ****      return xtype.get_scalar(obs_type, record, db_manager)
 weewx[2453] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/GTS.py", line 570, in get_scalar
 weewx[2453] ERROR weewx.cheetahgenerator: ****      return weewx.units.convertStd(__x,record['usUnits'])
 weewx[2453] ERROR weewx.cheetahgenerator: ****  TypeError: 'NoneType' object is not subscriptable

Problem line in GTS.py
                return weewx.units.convertStd(__x,record['usUnits'])

**Comment by roe-dl** [comment]
I understood the problem.
