### ISSUE TITLE
create observations and backfill?

### ISSUE THREAD

**Issue by silke-99** [roe-dl/weewx-GTS#30]
This might be a slightly stupid situation, but perhaps there is a way to get this running?
 
I have a long-running weewx installation which I moved to v5 about a month ago. The upgrade was slightly bumpy and for some reason my user dir is still in /usr/share/weewx/user (not sure why and how to change it, but thats another issue...)

I now installed this extension (and manually copied the *.py files to my user dir). Upon restart, observations were not created in the database automatically and I have created them manually.

However, I don't see the new observations being populated in the database. Most of them are NULL, just dayET got set to 0. I don't see any error messages. I played a bit with restarting weewx and rebuild-daily, no success so far.

**Update:** After fiddling once more with weewx.conf and replacing the auto-created  [[Calculations]] entries with the ones from this site, observations are now being populated.

Still,this question remains:

Is there a way to backfill the GTS observations for past years based on existing temperature/etc values?

Thanks! :-)

**Comment by roe-dl** [comment]
May be it helps to create a link from `/usr/share/weewx/user` to `/etc/weewx/bin`:

```shell
cd /etc/weewx/bin
sudo rm user
sudo ln -s /usr/share/weewx/user user
```

If `/etc/weewx/bin/user` already contains data, move them to `/usr/share/weewx/user` first.

Then check whether there are all the entries in `[StdWXCalculate][[Calculations]]` present, as described in section [Installation instructions](https://github.com/roe-dl/weewx-GTS?tab=readme-ov-file#installation-instructions) at item 3.

`weectl database calc-missing` could create the missing values, but I am not sure.

**Comment by silke-99** [comment]
Have to correct myself again - calc-missing actually works even though my first quick tests didn't generate any data.

It's just painfully slow and you'll have to ignore some errors. 

Now I'm running it in batches, I have >10 years of data, wish me luck :-)
