### ISSUE TITLE
update to latest version....best way...?

### ISSUE THREAD

**Issue by peters77** [roe-dl/weewx-GTS#8]
Hi,

I noticed there are some fixes since 0.4.1. 
What's the best way to update the nice addon you worte to 0.5.2!? 
Should I re-run the installer or just put the most recent GTS.py into bin/usr...?
Won't break my weewx instance so I ask before I will try..

Thanks in andvance!

Regards,

Christian

**Comment by roe-dl** [comment]
Both ways are possible and should work. Don't forget to do a backup before working on your installation.
