### ISSUE TITLE
UnknownAggregation error.... ?

### ISSUE THREAD

**Issue by peters77** [roe-dl/weewx-GTS#9]
Hi, 

I updated GTS to 0.5.2 but get errors in my logfile:

Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****  1577834878
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      obj.start()
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      self.run()
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 88, in get_series
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      aggregate_interval)
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 143, in get_series
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 105, in get_aggregate
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      **option_dict)
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 656, in get_aggregate
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      raise weewx.UnknownAggregation("%s undefinded aggregation %s" % (obs_type,aggregation_type))
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 381, in get_gts
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****      self.lock.release()
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****  KeyError: 1577834878
Jun 12 06:50:32 weewx weewx[547] ERROR weewx.reportengine:         ****  Generator terminated

switching back to 0.4.1 I get:

Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****  1577834878
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      obj.start()
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      self.run()
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 88, in get_series
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      aggregate_interval)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 143, in get_series
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 105, in get_aggregate
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      **option_dict)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 656, in get_aggregate
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      __x=self.get_gts(obs_type,__b,_soye_ts)
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 381, in get_gts
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****      __x=self.gts_values[soy_ts][dayOfGTSYear(sod_ts,soy_ts)]
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****  KeyError: 1577834878
Jun 12 07:00:39 weewx weewx[547] ERROR weewx.reportengine:         ****  Generator terminated

Any idea?

**Comment by roe-dl** [comment]
Could you provide the last 2 or 3 logging entries before the snippet above?

When the errors started to occur?

Please, switch on debugging in weewx.conf, then send the log including the debugging messages around the error.

**Comment by peters77** [comment]
There is no error or any interesting information before the section I sent. 
But some more lines of the 0.4.1 version log:

Jun 12 12:26:16 weewx weewx[18012] INFO user.forecast: MainThread: OWM: saved 40 forecast records
Jun 12 12:26:16 weewx weewx[18012] INFO user.forecast: MainThread: OWM: deleted forecasts prior to 1622888776
Jun 12 12:26:16 weewx weewx[18012] INFO weewx.restx: Windy: Published record 2021-06-12 12:26:00 CEST (1623493560)
Jun 12 12:26:16 weewx telegraf[30948]: 2021-06-12T10:26:16Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:26:17 weewx /weewxd: historygenerator.py: Generated 5 tables in 0.83 seconds
Jun 12 12:26:19 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 10 files for report Responsive in 3.21 seconds
Jun 12 12:26:26 weewx telegraf[30948]: 2021-06-12T10:26:26Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  1577834878
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      obj.start()
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.run()
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 88, in get_series
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 143, in get_series
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 105, in get_aggregate
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      **option_dict)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 656, in get_aggregate
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.get_gts(obs_type,__b,_soye_ts)
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 381, in get_gts
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.gts_values[soy_ts][dayOfGTSYear(sod_ts,soy_ts)]
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  KeyError: 1577834878
Jun 12 12:26:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Generator terminated
Jun 12 12:26:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/responsive
Jun 12 12:26:33 weewx weewx[18012] INFO user.stackedwindrose: Generated 1 images for StackedWindRose in 0.06 seconds
Jun 12 12:26:33 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 1 files for report WeatherBoardReport in 0.02 seconds
Jun 12 12:26:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weatherboard
Jun 12 12:26:36 weewx telegraf[30948]: 2021-06-12T10:26:36Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:26:46 weewx telegraf[30948]: 2021-06-12T10:26:46Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:26:56 weewx telegraf[30948]: 2021-06-12T10:26:56Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:06 weewx influxd[364]: [httpd] ::1 - - [12/Jun/2021:12:27:06 +0200] "POST /write?db=telegraf_metrics HTTP/1.1 " 204 0 "-" "Telegraf/1.18.3 Go/1.16.2" bc759e57-cb68-11eb-b9df-8e85591d1c9a 11028
Jun 12 12:27:06 weewx telegraf[30948]: 2021-06-12T10:27:06Z D! [outputs.influxdb] Wrote batch of 17 metrics in 13.012873ms
Jun 12 12:27:06 weewx telegraf[30948]: 2021-06-12T10:27:06Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:16 weewx weewx[18012] INFO weewx.manager: Added record 2021-06-12 12:27:00 CEST (1623493620) to database 'weewx_new'
Jun 12 12:27:16 weewx weewx[18012] INFO weewx.manager: Added record 2021-06-12 12:27:00 CEST (1623493620) to daily summary in 'weewx_new'
Jun 12 12:27:16 weewx telegraf[30948]: 2021-06-12T10:27:16Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:16 weewx weewx[18012] INFO weewx.restx: Windy: Published record 2021-06-12 12:27:00 CEST (1623493620)
Jun 12 12:27:17 weewx /weewxd: historygenerator.py: Generated 5 tables in 0.78 seconds
Jun 12 12:27:19 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 10 files for report Responsive in 3.22 seconds
Jun 12 12:27:26 weewx telegraf[30948]: 2021-06-12T10:27:26Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  1577834878
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      obj.start()
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.run()
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 88, in get_series
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 143, in get_series
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 105, in get_aggregate
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      **option_dict)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 656, in get_aggregate
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.get_gts(obs_type,__b,_soye_ts)
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 381, in get_gts
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.gts_values[soy_ts][dayOfGTSYear(sod_ts,soy_ts)]
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  KeyError: 1577834878
Jun 12 12:27:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Generator terminated
Jun 12 12:27:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/responsive
Jun 12 12:27:33 weewx weewx[18012] INFO user.stackedwindrose: Generated 1 images for StackedWindRose in 0.06 seconds
Jun 12 12:27:33 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 1 files for report WeatherBoardReport in 0.02 seconds
Jun 12 12:27:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weatherboard
Jun 12 12:27:36 weewx telegraf[30948]: 2021-06-12T10:27:36Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:46 weewx telegraf[30948]: 2021-06-12T10:27:46Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:27:56 weewx telegraf[30948]: 2021-06-12T10:27:56Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:28:06 weewx influxd[364]: [httpd] ::1 - - [12/Jun/2021:12:28:06 +0200] "POST /write?db=telegraf_metrics HTTP/1.1 " 204 0 "-" "Telegraf/1.18.3 Go/1.16.2" e0397f92-cb68-11eb-b9e0-8e85591d1c9a 10426
Jun 12 12:28:06 weewx telegraf[30948]: 2021-06-12T10:28:06Z D! [outputs.influxdb] Wrote batch of 17 metrics in 12.401777ms
Jun 12 12:28:06 weewx telegraf[30948]: 2021-06-12T10:28:06Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:28:16 weewx weewx[18012] INFO weewx.manager: Added record 2021-06-12 12:28:00 CEST (1623493680) to database 'weewx_new'
Jun 12 12:28:16 weewx weewx[18012] INFO weewx.manager: Added record 2021-06-12 12:28:00 CEST (1623493680) to daily summary in 'weewx_new'
Jun 12 12:28:16 weewx weewx[18012] INFO weewx.restx: Windy: Published record 2021-06-12 12:28:00 CEST (1623493680)
Jun 12 12:28:16 weewx telegraf[30948]: 2021-06-12T10:28:16Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:28:16 weewx /weewxd: historygenerator.py: Generated 5 tables in 0.73 seconds
Jun 12 12:28:19 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 10 files for report Responsive in 3.17 seconds
Jun 12 12:28:26 weewx telegraf[30948]: 2021-06-12T10:28:26Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.imagegenerator.ImageGenerator'
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  1577834878
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      obj.start()
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.run()
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 41, in run
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      self.genImages(self.gen_ts)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 181, in genImages
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval=aggregate_interval)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 88, in get_series
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      aggregate_interval)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 143, in get_series
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      agg_vt = get_aggregate(obs_type, stamp, do_aggregate, db_manager)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/xtypes.py", line 105, in get_aggregate
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      **option_dict)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 656, in get_aggregate
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.get_gts(obs_type,__b,_soye_ts)
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/GTS.py", line 381, in get_gts
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****      __x=self.gts_values[soy_ts][dayOfGTSYear(sod_ts,soy_ts)]
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  KeyError: 1577834878
Jun 12 12:28:33 weewx weewx[18012] ERROR weewx.reportengine:         ****  Generator terminated
Jun 12 12:28:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/responsive
Jun 12 12:28:33 weewx weewx[18012] INFO user.stackedwindrose: Generated 1 images for StackedWindRose in 0.07 seconds
Jun 12 12:28:33 weewx weewx[18012] INFO weewx.cheetahgenerator: Generated 1 files for report WeatherBoardReport in 0.02 seconds
Jun 12 12:28:33 weewx weewx[18012] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weatherboard

.....

I just turned on debugging, but the output is massive as I run some loop data service. Even there is no additional info or error regarding GTS except the lines I posted above....
I'm pretty sure there was no error I installed and started the GTS extension before I reach the GTS date? But I don't have a regular look on the syslog, so I really don't know when it started.

**Comment by roe-dl** [comment]
What happens, is, that WeeWX tries to get a GTS value for some day within the previous year, but the values were not calculated. For the moment I have no idea why.

Please, try the actual version from Github. Note, there is an additional file `dayboundarystats.py` that is necessary, too. I added some additional checks in the hope that will help.

**Comment by peters77** [comment]
I grab the most recent GTS.py and the addional file dayboundarystats.py. At the moment no errors since restart:

Jun 12 13:26:50 weewx weewx[23455] INFO user.GTS: Version 0.6b1
Jun 12 13:26:50 weewx weewx[23455] INFO user.GTS: Local mean time (LMT) UTC offset 0:32:01.440000
Jun 12 13:27:19 weewx weewx[23455] INFO user.GTS: GTS initialized 2021-01-01 00:27:58 
Jun 12 13:27:19 weewx weewx[23455] INFO user.GTS: GTS 789.3102527006172, 151 loops
Jun 12 13:27:35 weewx weewx[23455] INFO user.GTS: other year 2020-05-31
Jun 12 13:27:36 weewx weewx[23455] INFO user.GTS: GTS 1050.751793981481, 151 loops 

Let's see....! :-)

**Comment by roe-dl** [comment]
As there was no further reply I assume the issue is solved.

**Comment by peters77** [comment]
Sorry! Yes, all well, no more errors...issue resolved! Thanks! :-)
